---
name: CI - Master

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
    tags:
      - v*

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  pre-commit:
    name: Call Pre-Commit run
    uses: irishlab-io/.github/.github/workflows/reusable-pre-commit.yml@main

  secret:
    needs:
      - pre-commit
    name: Call Secret Scanning
    uses: irishlab-io/.github/.github/workflows/reusable-secret.yml@main
    secrets: inherit

  sca:
    needs:
      - pre-commit
    name: Placeholder - Software Composition Analysis
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Run SCA
        run: echo Software Composition Analysis
        shell: bash

  sast:
    needs:
      - pre-commit
    name: Call Static Application Security Testing
    uses: irishlab-io/.github/.github/workflows/reusable-sast.yml@main
    secrets: inherit

  unit-test:
    needs:
      - secret
      - sca
      - sast
    name: Placeholder - Unit & Integrations Tests
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Run U&IT
        run: echo Unit & Integrations Tests
        shell: bash
  
  docker-build-push:
    needs:
      - pre-commit
    name: Call Docker Build
    uses: irishlab-io/.github/.github/workflows/reusable-docker-build.yml@main

    permissions:
      contents: read
      packages: write
      pull-requests: write

    with:
      file: "./Dockerfile"
      platforms: |
          linux/amd64
